/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jon' at '3/15/17 5:31 PM' with Gradle 2.14.1
 *
 * @author jon, @date 3/15/17 5:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
